spring:
  profiles:
    active: local # 기본적으로 local이 선택된다는 뜻
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://3.34.144.33:3306/data?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: covid19

---

spring:
  profiles: local
server:
  port: 8079

---

debug: false

# 운영환경만의 설정
spring:
  profiles: production
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/test?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC"
    username: root
    password: 
server:
  port: 8081